version: '3'

services:
  mysql:
    build:
      context: ./mysql
    environment:
      - MYSQL_DATABASE=pretty_url
      - MYSQL_USER=user0
      - MYSQL_PASSWORD=passw0rD
      - MYSQL_ROOT_PASSWORD=gjjjtOe4
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql/data:/var/lib/mysql
    restart: always

  php:
    build:
      context: ./php
    depends_on:
      - mysql
    environment:
      - APP_ENV=prod
      - APP_SECRET=1d275fab6651093e16f4729ca69b275e
      - DATABASE_URL=mysql://user0:passw0rD@mysql:3306/pretty_url?serverVersion=5.7
    volumes:
      - ../:/var/www

  nginx:
    build:
      context: ./nginx
    depends_on:
      - php
    ports:
      - "8001:8001"
    volumes:
      - ../:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
